package com.example.ntb.ui.db;
import com.example.ntb.ui.city.bean.LocalAreasInfo;
import com.example.ntb.ui.city.bean.MessageDBInfo;
import com.example.ntb.ui.city.bean.PreferenceInfo;
import com.example.ntb.ui.city.bean.SelectedCityInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;
import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDBInfoDaoConfig;
    private final DaoConfig localAreasInfoDaoConfig;
    private final DaoConfig preferenceInfoDaoConfig;
    private final DaoConfig selectedCityInfoDaoConfig;

    private final MessageDBInfoDao messageDBInfoDao;
    private final LocalAreasInfoDao localAreasInfoDao;
    private final PreferenceInfoDao preferenceInfoDao;
    private final SelectedCityInfoDao selectedCityInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDBInfoDaoConfig = daoConfigMap.get(MessageDBInfoDao.class).clone();
        messageDBInfoDaoConfig.initIdentityScope(type);

        localAreasInfoDaoConfig = daoConfigMap.get(LocalAreasInfoDao.class).clone();
        localAreasInfoDaoConfig.initIdentityScope(type);

        preferenceInfoDaoConfig = daoConfigMap.get(PreferenceInfoDao.class).clone();
        preferenceInfoDaoConfig.initIdentityScope(type);

        selectedCityInfoDaoConfig = daoConfigMap.get(SelectedCityInfoDao.class).clone();
        selectedCityInfoDaoConfig.initIdentityScope(type);

        messageDBInfoDao = new MessageDBInfoDao(messageDBInfoDaoConfig, this);
        localAreasInfoDao = new LocalAreasInfoDao(localAreasInfoDaoConfig, this);
        preferenceInfoDao = new PreferenceInfoDao(preferenceInfoDaoConfig, this);
        selectedCityInfoDao = new SelectedCityInfoDao(selectedCityInfoDaoConfig, this);

        registerDao(MessageDBInfo.class, messageDBInfoDao);
        registerDao(LocalAreasInfo.class, localAreasInfoDao);
        registerDao(PreferenceInfo.class, preferenceInfoDao);
        registerDao(SelectedCityInfo.class, selectedCityInfoDao);
    }
    
    public void clear() {
        messageDBInfoDaoConfig.clearIdentityScope();
        localAreasInfoDaoConfig.clearIdentityScope();
        preferenceInfoDaoConfig.clearIdentityScope();
        selectedCityInfoDaoConfig.clearIdentityScope();
    }

    public MessageDBInfoDao getMessageDBInfoDao() {
        return messageDBInfoDao;
    }

    public LocalAreasInfoDao getLocalAreasInfoDao() {
        return localAreasInfoDao;
    }

    public PreferenceInfoDao getPreferenceInfoDao() {
        return preferenceInfoDao;
    }

    public SelectedCityInfoDao getSelectedCityInfoDao() {
        return selectedCityInfoDao;
    }

}
