package com.example.ntb.ui.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.example.ntb.ui.city.bean.SelectedCityInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "SELECTED_CITY_INFO".
*/
public class SelectedCityInfoDao extends AbstractDao<SelectedCityInfo, Long> {

    public static final String TABLENAME = "SELECTED_CITY_INFO";

    /**
     * Properties of entity SelectedCityInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property X = new Property(2, String.class, "x", false, "X");
        public final static Property Y = new Property(3, String.class, "y", false, "Y");
        public final static Property IsHome = new Property(4, boolean.class, "isHome", false, "IS_HOME");
    }


    public SelectedCityInfoDao(DaoConfig config) {
        super(config);
    }
    
    public SelectedCityInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SELECTED_CITY_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"X\" TEXT," + // 2: x
                "\"Y\" TEXT," + // 3: y
                "\"IS_HOME\" INTEGER NOT NULL );"); // 4: isHome
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SELECTED_CITY_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SelectedCityInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String x = entity.getX();
        if (x != null) {
            stmt.bindString(3, x);
        }
 
        String y = entity.getY();
        if (y != null) {
            stmt.bindString(4, y);
        }
        stmt.bindLong(5, entity.getIsHome() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SelectedCityInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String x = entity.getX();
        if (x != null) {
            stmt.bindString(3, x);
        }
 
        String y = entity.getY();
        if (y != null) {
            stmt.bindString(4, y);
        }
        stmt.bindLong(5, entity.getIsHome() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SelectedCityInfo readEntity(Cursor cursor, int offset) {
        SelectedCityInfo entity = new SelectedCityInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // x
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // y
            cursor.getShort(offset + 4) != 0 // isHome
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SelectedCityInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setX(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setY(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsHome(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SelectedCityInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SelectedCityInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SelectedCityInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
